apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-pipeline-ci-pipeline
spec:
  params:
  - name: buildUUID
    description: UUID used to track a CI Pipeline Run in logs
  - name: sourceEventId
    description: The event ID from the SCM (e.g. X-GitHub-Delivery)
  - name: package
    description: org/repo
  - name: pullRequestNumber
    description: The pullRequestNumber
  - name: pullRequestUrl
    description: The HTML URL for the pull request
  - name: pullRequestBaseRef
    description: |
      The base git ref for the pull request. This is the branch the
      pull request would merge onto once approved.
  - name: gitRepository
    description: The git repository that hosts context and Dockerfile
  - name: gitRevision
    description: The Git revision to be used.
  - name: gitCloneDepth
    description: Number of commits in the change + 1
  - name: gitHubCommand
    description: |
      The GitHub command that was used a trigger. This is only available when
      this template is triggered by a comment. The default value is for the
      case of a pull_request event.
    default: ""
  - name: labels
    description: List of labels currently on the Pull Request
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pull-pipeline-kind-k8s-v1-21-e2e-
      labels:
        prow.k8s.io/build-id: $(tt.params.buildUUID)
        tekton.dev/source-event-id: $(tt.params.sourceEventId)
        tekton.dev/kind: ci
        tekton.dev/check-name: pull-pipeline-kind-k8s-v1-21-e2e
        tekton.dev/pr-number: $(tt.params.pullRequestNumber)
      annotations:
        tekton.dev/gitRevision: "$(tt.params.gitRevision)"
        tekton.dev/gitURL: "$(tt.params.gitRepository)"
    spec:
      serviceAccountName: tekton-ci-jobs
      workspaces:
        - name: sources
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: credentials
          secret:
            secretName: "release-secret"
      pipelineRef:
        name: kind-e2e
      params:
        - name: pullRequestNumber
          value: $(tt.params.pullRequestNumber)
        - name: pullRequestBaseRef
          value: $(tt.params.pullRequestBaseRef)
        - name: gitRepository
          value: "$(tt.params.gitRepository)"
        - name: gitCloneDepth
          value: $(tt.params.gitCloneDepth)
        - name: fileFilterRegex
          value: '^(cmd/|examples/|images/|pkg/|test/|go\.)'
        - name: checkName
          value: pull-pipeline-kind-k8s-v1-21-e2e
        - name: gitHubCommand
          value: $(tt.params.gitHubCommand)
        - name: k8s-version
          value: v1.21.x
        - name: e2e-script
          value: test/e2e-tests.sh
        - name: e2e-env
          value: test/e2e-tests-kind.env
