apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-cd-trigger
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            env:
              - name: NAMESPACE
                value: "eu-geo"
              - name: CLUSTER_RESOURCE
                value: "robocat-cadmin"
              - name: CHART_NAME
                value: "minio"
              - name: CHART_VERSION
                value: "8.0.8"
              - name: CHART_PARAMS
                value: >-
                  fullnameOverride=s3,
                  serviceAccount.name=minio,
                  persistence.enabled=false,
                  buckets={tekton-pipelines},
                  defaultBucket.enabled=true,
                  defaultBucket.purge=false
              - name: CHART_DESCRIPTION
                value: "minio-s3"
              - name: CHART_REPO
                value: https://helm.min.io/
