apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-cron-trigger
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            env:
              - name: PROJECT_NAME
                value: cloudevents
          initContainers:
          - name: git
            env:
              - name: GIT_REPO
                value: github.com/tektoncd/experimental
