apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-cd-trigger
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            env:
              - name: NAMESPACE
                value: "cert-manager"
              - name: CLUSTER_RESOURCE
                value: "robocat-cadmin"
              - name: CHART_NAME
                value: "cert-manager"
              - name: CHART_VERSION
                value: "v1.10.1"
              - name: CHART_PARAMS
                value: fullnameOverride=cert-manager,installCRDs=true
              - name: CHART_DESCRIPTION
                value: "cert-manager"
              - name: CHART_REPO
                value: https://charts.jetstack.io
