namePrefix: nightly-release-
commonAnnotations:
  release: nightly
resources:
- template.yaml
- trigger.yaml
configurations:
- kustomizeconfig/eventlistener.yaml
- kustomizeconfig/pipeline.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: tekton.plumbing
