apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-taskrun-cloudevent
spec:
  params:
  - name: pullRequestNumber
    value: $(body.taskRun.metadata.labels.tekton\.dev/pr-number)
  - name: gitRevision
    value: $(body.taskRun.metadata.annotations.tekton\.dev/gitRevision)
  - name: buildUUID
    value: $(body.taskRun.metadata.labels.prow\.k8s\.io/build-id)
  - name: checkName
    value: $(body.taskRun.metadata.labels.tekton\.dev/check-name)
  - name: taskRunName
    value: $(body.taskRun.metadata.name)
  - name: taskRunNamespace
    value: $(body.taskRun.metadata.namespace)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-check-pending
spec:
  params:
  - name: gitHubCheckStatus
    value: pending
  - name: gitHubCheckDescription
    value: "Job Triggered."
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-check-success
spec:
  params:
  - name: gitHubCheckStatus
    value: success
  - name: gitHubCheckDescription
    value: "Job Successful."
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-check-failure
spec:
  params:
  - name: gitHubCheckStatus
    value: failure
  - name: gitHubCheckDescription
    value: "Job Failed."
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-taskrun-from-pipelinerun-cloudevent
spec:
  params:
  - name: parentPipelineRunName
    value: $(body.taskRun.metadata.ownerReferences[?(@.kind == 'PipelineRun')].name)
  - name: parentPipelineRunTaskName
    value: $(body.taskRun.metadata.labels.tekton\.dev/pipelineTask)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-overlays
spec:
  params:
  - name: gitHubRepo
    value: $(extensions.repo)
  - name: shortBuildUUID
    value: $(extensions.shortBuildUUID)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-ci-github-repo-underscore
spec:
  params:
  - name: gitHubRepo
    value: $(extensions.repo)
  - name: gitHubRepoUnderscore
    value: $(extensions.repoUnderscore)
  - name: shortBuildUUID
    value: $(extensions.shortBuildUUID)