namePrefix: tekton-verified-catalog-
bases:
  - ../../base

patches:
  - path: template.yaml
    target:
      group: triggers.tekton.dev
      version: v1beta1
      kind: TriggerTemplate
      name: ci-pipeline
