apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: slack-notification-of-cd-failure
  labels:
    cd.tekton.dev/trigger-type: failure-notification
spec:
  interceptors:
    - ref:
        name: cel
        kind: ClusterInterceptor
      params:
        - name: "filter"
          value: >-
            body.taskRun.metadata.labels['triggers.tekton.dev/eventlistener'] == 'tekton-cd' &&
            body.taskRun.metadata.labels['triggers.tekton.dev/trigger'] in ['configmaps', 'folders', 'helm']
  bindings:
  - ref: cd-pipeline-type
  - ref: taskrun-meta
  - ref: dashboard-url-dogfooding
  template:
    ref: cd-pipeline-failed-slack
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: slack-notification-of-nightly-failure
  labels:
    cd.tekton.dev/trigger-type: failure-notification
spec:
  interceptors:
    - ref:
        name: cel
        kind: ClusterInterceptor
      params:
        - name: "filter"
          value: >-
            body.taskRun.metadata.labels['triggers.tekton.dev/eventlistener'].endsWith('nightly-release-cron') &&
            body.taskRun.metadata.labels['triggers.tekton.dev/trigger'].endsWith('nightly-release-cron-trigger')
  bindings:
  - ref: cd-pipeline-type-nightly
  - ref: pipelinerun-meta
  - ref: dashboard-url-dogfooding
  template:
    ref: cd-pipeline-failed-slack
