namePrefix: tekton-catalog-
bases:
  - ../../bases

patches:
  - path: template.yaml
    target:
      group: triggers.tekton.dev
      version: v1beta1
      kind: TriggerTemplate
      name: ci-pipeline
  - path: trigger.yaml
    target:
      group: triggers.tekton.dev
      version: v1beta1
      kind: Trigger
