---
apiVersion: custom.tekton.dev/v1alpha1
kind: TaskLoop
metadata:
  name: golang-tests
spec:
  iterateParam: context
  taskRef:
    name: golang-test
    bundle: gcr.io/tekton-releases/catalog/upstream/golang-test:0.1
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-golang-tests
  annotations:
    description: |
      Run unit tests against a list of root folders.
      Requires the task-loops controller.
spec:
  params:
    - name: pullRequestNumber
      description: The pullRequestNumber
    - name: pullRequestBaseRef
      description: The pull request base branch
    - name: gitRepository
      description: The git repository that hosts context and Dockerfile
    - name: gitCloneDepth
      description: Number of commits in the change + 1
    - name: fileFilterRegex
      description: Names regex to be matched in the list of modified files
    - name: checkName
      description: The name of the GitHub check that this pipeline is used for
    - name: gitHubCommand
      description: The command that was used to trigger testing
    - name: package
      description: package (and its children) under test
    - name: folders
      type: array
      description: The folders to test
  workspaces:
    - name: sources
      description: Workspace where the git repo is prepared for testing
  tasks:
    - name: clone-repo
      taskRef:
        name: git-batch-merge
        bundle: gcr.io/tekton-releases/catalog/upstream/git-batch-merge:0.2
      params:
        - name: url
          value: $(params.gitRepository)
        - name: mode
          value: "merge"
        - name: revision
          value: $(params.pullRequestBaseRef)
        - name: refspec
          value: refs/heads/$(params.pullRequestBaseRef):refs/heads/$(params.pullRequestBaseRef)
        - name: batchedRefs
          value: "refs/pull/$(params.pullRequestNumber)/head"
      workspaces:
        - name: output
          workspace: sources
    - name: check-name-matches
      taskRef:
        name: check-name-matches
      params:
        - name: gitHubCommand
          value: $(params.gitHubCommand)
        - name: checkName
          value: $(params.checkName)
    - name: check-git-files-changed
      runAfter: ['clone-repo']
      taskRef:
        name: check-git-files-changed
      params:
        - name: gitCloneDepth
          value: $(params.gitCloneDepth)
        - name: regex
          value: $(params.fileFilterRegex)
      workspaces:
        - name: input
          workspace: sources
    - name: unit-tests
      when:  # implicit dependency on the check tasks
      - input: $(tasks.check-name-matches.results.check)
        operator: in
        values: ["passed"]
      - input: $(tasks.check-git-files-changed.results.check)
        operator: in
        values: ["passed"]
      taskRef:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: TaskLoop
        name: golang-tests
      params:
      - name: package
        value: "$(params.package)"
      - name: context
        value: [$(params.folders)]
      - name: version
        value: "1.15"
      workspaces:
        - name: source
          workspace: sources