namePrefix: add-pr-body-
resources:
- github.com/tektoncd/plumbing/tekton/ci/interceptors/add-pr-body/tekton/?ref=main
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: template.yaml
  target:
    group: triggers.tekton.dev
    kind: TriggerTemplate
    name: template
    version: v1alpha1
- path: trigger.yaml
  target:
    group: triggers.tekton.dev
    kind: Trigger
    name: nightly
    version: v1alpha1
