apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: peribolos-binding
spec:
  params:
    - name: gitRevision
      value: $(body.head_commit.id)
    - name: gitRepository
      value: $(body.repository.url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: peribolos-template
spec:
  params:
    - name: gitRevision
      description: The git revision
      default: main
    - name: gitRepository
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: peribolos-run-
      spec:
        pipelineRef:
          name: peribolos-sync
        params:
          - name: url
            value: $(tt.params.gitRepository)
          - name: revision
            value: $(tt.params.gitRevision)
        workspaces:
          - name: github-oauth
            secret:
              secretName: peribolos-token-github
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: peribolos-trigger
spec:
  serviceAccountName: release-right-meow
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  triggers:
    - name: peribolos-trigger
      interceptors:
        - ref:
            name: cel
            kind: ClusterInterceptor
          params:
            - name: filter
              value: >-
                header.match('X-GitHub-Event', 'push') &&
                'repository' in body &&
                'ref' in body &&
                body['repository']['full_name'] == 'tektoncd/community' &&
                body['repository']['fork'] == false &&
                body['ref'] == 'refs/heads/main'
      bindings:
        - ref: peribolos-binding
      template:
        ref: peribolos-template
